import json
from pathlib import Path

qtile_dir = Path("~/.config/qtile").expanduser()

# theme file generated by nixos
theme = qtile_dir / "colors.json"
if not theme.exists():
    theme = theme.with_name("default_colors.json")
with open(theme) as theme_file:
    colors = json.load(theme_file)
powerline_colors = colors["powerline-colors"]
